In [100]:
PRE_DIR  <- "../../data/preprocessed_rds_files"
CLIN_DIR <- "../../data/raw_clinical_rds_files"
DEG_DIR     <- "../../data/deg_rds_files"
RESULTS_DIR <- "../../results/deg"
DATA_DIR    <- "../../data"

datasets        <- c("GSE42568", "GSE21653", "GSE20711", "GSE88770")
SIGNATURE_GENES <- c("TSLP", "BIRC5", "S100B", "MDK", "S100P", "RARRES3", "BLNK", "ACO1")

RAW_RFS_COLS <- c(
    GSE42568 = "relapse free survival time_days:ch1",
    GSE21653 = "dfs time (months):ch1",
    GSE20711 = "t.rfs:ch1",
    GSE88770 = "drfs_or_last_contact_years:ch1"
)

In [101]:
view_preprocessed <- function(name) {
    expr     <- readRDS(file.path(PRE_DIR, paste0(name, "_expression_matrix.rds")))
    clinical <- readRDS(file.path(PRE_DIR, paste0(name, "_clinical_metadata.rds")))
    clinical
}

view_raw_clinical <- function(name) {
    df <- readRDS(file.path(CLIN_DIR, paste0(name, "_raw_clinical.rds")))
    cat("Dataset:", name, "|", nrow(df), "samples x", ncol(df), "columns\n\n")
    for (col in colnames(df)) {
        vals     <- df[[col]]
        n_unique <- length(unique(vals))
        cat(sprintf("  %-50s [%d unique]  ", col, n_unique))
        if (n_unique <= 15) {
            cat(paste(sort(unique(vals)), collapse = " | "))
        } else {
            cat(class(vals), "— e.g.", paste(head(unique(vals), 3), collapse = ", "), "...")
        }
        cat("\n")
    }
    invisible(df)
}

summarise_rfs_time <- function(name) {
    df   <- readRDS(file.path(CLIN_DIR, paste0(name, "_raw_clinical.rds")))
    col  <- RAW_RFS_COLS[[name]]
    vals <- as.numeric(df[[col]])
    cat("RFS time raw distribution —", name, "\n")
    cat("Column:", col, "\n\n")
    print(summary(vals))
    invisible(vals)
}

In [102]:
head(view_raw_clinical(datasets[1]))

Dataset: GSE42568 | 121 samples x 50 columns

  title                                              [121 unique]  character — e.g. Normal breast, N1_15_12_04, Normal breast, N4_14_12_04, Normal breast, N5_15_12_04 ...
  geo_accession                                      [121 unique]  character — e.g. GSM1045191, GSM1045192, GSM1045193 ...
  status                                             [1 unique]  Public on May 26 2013
  submission_date                                    [1 unique]  Nov 27 2012
  last_update_date                                   [1 unique]  Jul 30 2013
  type                                               [1 unique]  RNA
  channel_count                                      [1 unique]  1
  source_name_ch1                                    [2 unique]  Breast tissue, cancer | Breast tissue, normal
  organism_ch1                                       [1 unique]  Homo sapiens
  characteristics_ch1                                [2 unique]  tissue: breast cancer | tissue: normal breast
  characteristics_ch1.1                              [103 unique]  character — e.g. age: NA, age: 74.03, age: 67.26 ...
  characteristics_ch1.2                              [3 unique]  er_status: 0 | er_status: 1 | er_status: NA
  characteristics_ch1.3                              [25 unique]  character — e.g. size: NA, size: 0.6, size: 5 ...
  characteristics_ch1.4                              [4 unique]  grade: 1 | grade: 2 | grade: 3 | grade: NA
  characteristics_ch1.5                              [3 unique]  lymph node status: 0 | lymph node status: 1 | lymph node status: NA
  characteristics_ch1.6                              [100 unique]  character — e.g. relapse free survival time_days: NA, relapse free survival time_days: 3026, relapse free survival time_days: 755 ...
  characteristics_ch1.7                              [3 unique]  relapse free survival event: 0 | relapse free survival event: 1 | relapse free survival event: NA
  characteristics_ch1.8                              [103 unique]  character — e.g. overall survival time_days: NA, overall survival time_days: 3026, overall survival time_days: 755 ...
  characteristics_ch1.9                              [3 unique]  overall survival event: 0 | overall survival event: 1 | overall survival event: NA
  treatment_protocol_ch1                             [1 unique]  Tissues were stored at -70°C/-80°C prior to RNA isolation.
  molecule_ch1                                       [1 unique]  total RNA
  extract_protocol_ch1                               [1 unique]  Samples were homogenised, on ice, in 1 ml TriReagent (Sigma; Poole, UK) and total RNA was subsequently isolated according to the manufacturer's instructions. RNA quantity and purity were assessed at 260 nm and 280 nm using a Nanodrop (ND-1000; Labtech. International); an Agilent Bioanalyser (Agilent 2100; Agilent Technologies) was used to assess RNA qualitatively after isolation and, subsequently, following biotin-labelling and after fragmentation.
  label_ch1                                          [1 unique]  biotin
  label_protocol_ch1                                 [1 unique]  100 ng of each specimen was amplified and labelled using the Affymetrix GeneChip Eukaryotic 2 Cycle Labelling Assays for Expression Analysis, (Affymetrix; 900494) according to the manufacturer's instructions (www.affymetrix.com/products/reagents/specific/cdna2.affx).
  taxid_ch1                                          [1 unique]  9606
  hyb_protocol                                       [1 unique]  Hybridisation solution (1 mol/l NaCl, 20 mmol/1 EDTA, 100 mmol/1 2-(N-morpholino) ethanesulfonic acid, and 0.01% Tween 20) was used to pre-hybridise Affymetrix U133 Plus 2.0 oligonucleotide microarrays for 10 minutes at 45°C and 60 rpm. The pre-hybridisation solution was removed and replaced with 200 μl hybridisation solution containing 0.05 μg/μl fragmented cRNA. The arrays were hybridised for 16 hours at 45°C and 60 rpm. Arrays were subsequently washed (Affymetrix Fluidics Station 400) and stained with streptavidin-phycoerythrin (Stain Buffer, 2 mg/ml acetylated BSA and 10 μg/ml streptavidin R-phycoerythrin; Molecular Probes, Inc., Eugene, OR).
  scan_protocol                                      [1 unique]  Arrays were scanned on an Affymetrix GCS GeneChip GeneArray scanner. Resulting data was analysed using GCOS, dCHIP, and GeneSpring (Agilent Technologies).
  description                                        [2 unique]  Breast cancer data. | Normal breast tissue data.
  data_processing                                    [1 unique]  All microarray data were called using the GC robust multichip average method (GC-RMA). R and Bioconductor - GCRMA package.
  platform_id                                        [1 unique]  GPL570
  contact_name                                       [1 unique]  Colin ,,Clarke
  contact_email                                      [1 unique]  colin.clarke@dcu.ie
  contact_department                                 [1 unique]  NICB
  contact_institute                                  [1 unique]  Dublin City University
  contact_address                                    [1 unique]  Collin's Av.
  contact_city                                       [1 unique]  Dublin
  contact_zip/postal_code                            [1 unique]  Dublin 9
  contact_country                                    [1 unique]  Ireland
  supplementary_file                                 [121 unique]  character — e.g. ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1045nnn/GSM1045191/suppl/GSM1045191_N1_15_12_04.CEL.gz, ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1045nnn/GSM1045192/suppl/GSM1045192_N4_14_12_04.CEL.gz, ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1045nnn/GSM1045193/suppl/GSM1045193_N5_15_12_04.CEL.gz ...
  data_row_count                                     [1 unique]  54675
  age:ch1                                            [103 unique]  character — e.g. NA, 74.03, 67.26 ...
  er_status:ch1                                      [3 unique]  0 | 1 | NA
  grade:ch1                                          [4 unique]  1 | 2 | 3 | NA
  lymph node status:ch1                              [3 unique]  0 | 1 | NA
  overall survival event:ch1                         [3 unique]  0 | 1 | NA
  overall survival time_days:ch1                     [103 unique]  character — e.g. NA, 3026, 755 ...
  relapse free survival event:ch1                    [3 unique]  0 | 1 | NA
  relapse free survival time_days:ch1                [100 unique]  character — e.g. NA, 3026, 755 ...
  size:ch1                                           [25 unique]  character — e.g. NA, 0.6, 5 ...
  tissue:ch1                                         [2 unique]  breast cancer | normal breast

           title                      geo_accession status
GSM1045191 Normal breast, N1_15_12_04 GSM1045191    Public on May 26 2013
GSM1045192 Normal breast, N4_14_12_04 GSM1045192    Public on May 26 2013
GSM1045193 Normal breast, N5_15_12_04 GSM1045193    Public on May 26 2013
GSM1045194 Normal breast, N6_14_12_04 GSM1045194    Public on May 26 2013
GSM1045195 Normal breast, P1_15_12_04 GSM1045195    Public on May 26 2013
GSM1045196 Normal breast, P10_26_1_05 GSM1045196    Public on May 26 2013
           submission_date last_update_date type channel_count
GSM1045191 Nov 27 2012     Jul 30 2013      RNA  1
GSM1045192 Nov 27 2012     Jul 30 2013      RNA  1
GSM1045193 Nov 27 2012     Jul 30 2013      RNA  1
GSM1045194 Nov 27 2012     Jul 30 2013      RNA  1
GSM1045195 Nov 27 2012     Jul 30 2013      RNA  1
GSM1045196 Nov 27 2012     Jul 30 2013      RNA  1
           source_name_ch1       organism_ch1 characteristics_ch1   ⋯ age:ch1
GSM1045191 Breast tissue, normal Homo sapiens tissue: normal breast ⋯ NA
GSM1045192 Breast tissue, normal Homo sapiens tissue: normal breast ⋯ NA
GSM1045193 Breast tissue, normal Homo sapiens tissue: normal breast ⋯ NA
GSM1045194 Breast tissue, normal Homo sapiens tissue: normal breast ⋯ NA
GSM1045195 Breast tissue, normal Homo sapiens tissue: normal breast ⋯ NA
GSM1045196 Breast tissue, normal Homo sapiens tissue: normal breast ⋯ NA
           er_status:ch1 grade:ch1 lymph node status:ch1
GSM1045191 NA            NA        NA
GSM1045192 NA            NA        NA
GSM1045193 NA            NA        NA
GSM1045194 NA            NA        NA
GSM1045195 NA            NA        NA
GSM1045196 NA            NA        NA
           overall survival event:ch1 overall survival time_days:ch1
GSM1045191 NA                         NA
GSM1045192 NA                         NA
GSM1045193 NA                         NA
GSM1045194 NA                         NA
GSM1045195 NA                         NA
GSM1045196 NA                         NA
           relapse free survival event:ch1 relapse free survival time_days:ch1
GSM1045191 NA                              NA
GSM1045192 NA                              NA
GSM1045193 NA                              NA
GSM1045194 NA                              NA
GSM1045195 NA                              NA
GSM1045196 NA                              NA
           size:ch1 tissue:ch1
GSM1045191 NA       normal breast
GSM1045192 NA       normal breast
GSM1045193 NA       normal breast
GSM1045194 NA       normal breast
GSM1045195 NA       normal breast
GSM1045196 NA       normal breast

In [103]:
summarise_rfs_time(datasets[1])

Warning message in summarise_rfs_time(datasets[1]):
"NAs introduced by coercion"

RFS time raw distribution — GSE42568
Column: relapse free survival time_days:ch1

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's
   84.0   595.8  1907.0  1633.2  2485.2  3026.0      17

In [104]:
colnames(view_preprocessed(datasets[1]))

[1] "geo_accession"     "is_tumor"          "rfs_event"
[4] "rfs_time"          "er_status"         "tumor_grade"
[7] "lymph_node_status" "t_stage"

In [105]:
tail(view_preprocessed(datasets[1]))

    geo_accession is_tumor rfs_event rfs_time er_status tumor_grade
116 GSM1045202    0        NA        NA       NA        NA
117 GSM1045203    0        NA        NA       NA        NA
118 GSM1045204    0        NA        NA       NA        NA
119 GSM1045205    0        NA        NA       NA        NA
120 GSM1045206    0        NA        NA       NA        NA
121 GSM1045207    0        NA        NA       NA        NA
    lymph_node_status t_stage
116 NA                NA
117 NA                NA
118 NA                NA
119 NA                NA
120 NA                NA
121 NA                NA

In [106]:
# should be 121

nrow(view_preprocessed(datasets[1]))

[1] 121

In [107]:
head(view_raw_clinical(datasets[2]))

Dataset: GSE21653 | 266 samples x 62 columns

  title                                              [266 unique]  character — e.g. BC1, BC2, BC3 ...
  geo_accession                                      [266 unique]  character — e.g. GSM540108, GSM540109, GSM540110 ...
  status                                             [1 unique]  Public on May 05 2010
  submission_date                                    [1 unique]  May 04 2010
  last_update_date                                   [2 unique]  Aug 19 2011 | Aug 28 2018
  type                                               [1 unique]  RNA
  channel_count                                      [1 unique]  1
  source_name_ch1                                    [1 unique]  human breast cancer tumors
  organism_ch1                                       [1 unique]  Homo sapiens
  characteristics_ch1                                [60 unique]  character — e.g. age at diagnosis: 67, age at diagnosis: 47, age at diagnosis: 41 ...
  characteristics_ch1.1                              [9 unique]  histology: IDC | histology: ILC | histology: MIX | histology: MUC | histology: other | histology: TUB | pn: 1 | pn: NA | pt: pT2
  characteristics_ch1.2                              [8 unique]  pn: 0 | pn: 1 | pn: NA | pt: pT1 | pt: pT2 | pt: pT3 | sbr grade: 3 | sbr grade: NA
  characteristics_ch1.3                              [9 unique]  er ihc: 0 | er ihc: 1 | er ihc: NA | pn: 0 | pn: 1 | pn: NA | sbr grade: 2 | sbr grade: 3 | sbr grade: NA
  characteristics_ch1.4                              [9 unique]  er ihc: 0 | er ihc: 1 | er ihc: NA | pr ihc: 0 | pr ihc: NA | sbr grade: 1 | sbr grade: 2 | sbr grade: 3 | sbr grade: NA
  characteristics_ch1.5                              [8 unique]  er ihc: 0 | er ihc: 1 | er ihc: NA | erbb2: 1 | erbb2: NA | pr ihc: 0 | pr ihc: 1 | pr ihc: NA
  characteristics_ch1.6                              [8 unique]  erbb2: 0 | erbb2: 1 | erbb2: NA | p53 ihc: 1 | p53 ihc: NA | pr ihc: 0 | pr ihc: 1 | pr ihc: NA
  characteristics_ch1.7                              [7 unique]  erbb2: 0 | erbb2: 1 | erbb2: NA | ki67 ihc: 1 | ki67 ihc: NA | p53 ihc: 1 | p53 ihc: NA
  characteristics_ch1.8                              [7 unique]  dfs evt: 1 | dfs evt: NA | ki67 ihc: 1 | ki67 ihc: NA | p53 ihc: 0 | p53 ihc: 1 | p53 ihc: NA
  characteristics_ch1.9                              [9 unique]  dfs evt: 0 | dfs evt: 1 | dfs evt: NA | dfs time (months): 16.30 | dfs time (months): 19.65 | ki67 ihc: 0 | ki67 ihc: 1 | ki67 ihc: NA | molecular subtype: ERBB2
  characteristics_ch1.10                             [12 unique]  dfs evt: 0 | dfs evt: 1 | dfs evt: NA | dfs time (months): 0.00 | dfs time (months): 10.00 | dfs time (months): 113.77 | dfs time (months): 222.29 | dfs time (months): 37.62 | dfs time (months): 51.84 | molecular subtype: LuminalB | molecular subtype: Normal | tissue: breast cancer tumor
  characteristics_ch1.11                             [242 unique]  character — e.g. dfs time (months): 24.02, tissue: breast cancer tumor, dfs time (months): 58.15 ...
  characteristics_ch1.12                             [7 unique]   | molecular subtype: Basal | molecular subtype: ERBB2 | molecular subtype: LuminalA | molecular subtype: LuminalB | molecular subtype: Normal | tissue: breast cancer tumor
  characteristics_ch1.13                             [2 unique]   | tissue: breast cancer tumor
  molecule_ch1                                       [1 unique]  total RNA
  extract_protocol_ch1                               [1 unique]  Guanidinium isothiocyanate and centrifugation over a cesium chloride gradient.
  label_ch1                                          [1 unique]  biotin
  label_protocol_ch1                                 [1 unique]  Affymetrix standard protocol
  taxid_ch1                                          [1 unique]  9606
  hyb_protocol                                       [1 unique]  Affymetrix standard protocol
  scan_protocol                                      [1 unique]  Affymetrix standard protocol
  description                                        [1 unique]  n/a
  data_processing                                    [1 unique]  RMA using a quantile normalization
  platform_id                                        [1 unique]  GPL570
  contact_name                                       [1 unique]  Pascal,,FINETTI
  contact_email                                      [1 unique]  finettip@ipc.unicancer.fnclcc.fr
  contact_phone                                      [1 unique]  (33)+4 91 22 33 04
  contact_laboratory                                 [1 unique]  Molecular Oncology
  contact_department                                 [1 unique]  Centre de cancérologie de Marseille
  contact_institute                                  [1 unique]  Institut Paoli-Calmettes
  contact_address                                    [1 unique]  232 Bd Ste Marguerite
  contact_city                                       [1 unique]  Marseille
  contact_state                                      [1 unique]  BdR
  contact_zip/postal_code                            [1 unique]  13009
  contact_country                                    [1 unique]  France
  supplementary_file                                 [266 unique]  character — e.g. ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM540nnn/GSM540108/suppl/GSM540108_160306-23.CEL.gz, ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM540nnn/GSM540109/suppl/GSM540109_060406-05.CEL.gz, ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM540nnn/GSM540110/suppl/GSM540110_200406-16.CEL.gz ...
  data_row_count                                     [1 unique]  54613
  relation                                           [265 unique]  character — e.g. Reanalyzed by: GSM781322, Reanalyzed by: GSM781323, Reanalyzed by: GSM781324 ...
  relation.1                                         [2 unique]   | Reanalyzed by: GSE119087
  age at diagnosis:ch1                               [60 unique]  character — e.g. 67, 47, 41 ...
  dfs evt:ch1                                        [3 unique]  0 | 1 | NA
  dfs time (months):ch1                              [242 unique]  character — e.g. 24.02, 16.30, 19.65 ...
  er ihc:ch1                                         [3 unique]  0 | 1 | NA
  erbb2:ch1                                          [3 unique]  0 | 1 | NA
  histology:ch1                                      [7 unique]  IDC | ILC | MIX | MUC | other | TUB
  ki67 ihc:ch1                                       [3 unique]  0 | 1 | NA
  molecular subtype:ch1                              [5 unique]  Basal | ERBB2 | LuminalA | LuminalB | Normal
  p53 ihc:ch1                                        [3 unique]  0 | 1 | NA
  pn:ch1                                             [3 unique]  0 | 1 | NA
  pr ihc:ch1                                         [3 unique]  0 | 1 | NA
  pt:ch1                                             [4 unique]  pT1 | pT2 | pT3
  sbr grade:ch1                                      [4 unique]  1 | 2 | 3 | NA
  tissue:ch1                                         [1 unique]  breast cancer tumor

          title geo_accession status                submission_date
GSM540108 BC1   GSM540108     Public on May 05 2010 May 04 2010
GSM540109 BC2   GSM540109     Public on May 05 2010 May 04 2010
GSM540110 BC3   GSM540110     Public on May 05 2010 May 04 2010
GSM540111 BC4   GSM540111     Public on May 05 2010 May 04 2010
GSM540112 BC5   GSM540112     Public on May 05 2010 May 04 2010
GSM540113 BC6   GSM540113     Public on May 05 2010 May 04 2010
          last_update_date type channel_count source_name_ch1
GSM540108 Aug 28 2018      RNA  1             human breast cancer tumors
GSM540109 Aug 28 2018      RNA  1             human breast cancer tumors
GSM540110 Aug 28 2018      RNA  1             human breast cancer tumors
GSM540111 Aug 28 2018      RNA  1             human breast cancer tumors
GSM540112 Aug 28 2018      RNA  1             human breast cancer tumors
GSM540113 Aug 28 2018      RNA  1             human breast cancer tumors
          organism_ch1 characteristics_ch1  ⋯ erbb2:ch1 histology:ch1
GSM540108 Homo sapiens age at diagnosis: 67 ⋯ 0         IDC
GSM540109 Homo sapiens age at diagnosis: 47 ⋯ 1         NA
GSM540110 Homo sapiens age at diagnosis: 41 ⋯ 1         NA
GSM540111 Homo sapiens age at diagnosis: 62 ⋯ 1         IDC
GSM540112 Homo sapiens age at diagnosis: 60 ⋯ 0         IDC
GSM540113 Homo sapiens age at diagnosis: 51 ⋯ 0         IDC
          ki67 ihc:ch1 molecular subtype:ch1 p53 ihc:ch1 pn:ch1 pr ihc:ch1
GSM540108 NA           LuminalB              0           1      0
GSM540109 1            LuminalB              1           1      0
GSM540110 1            LuminalB              1           1      0
GSM540111 NA           ERBB2                 1           1      0
GSM540112 0            LuminalA              0           1      1
GSM540113 NA           Normal                0           1      0
          pt:ch1 sbr grade:ch1 tissue:ch1
GSM540108 pT2    2             breast cancer tumor
GSM540109 NA     3             breast cancer tumor
GSM540110 NA     3             breast cancer tumor
GSM540111 pT1    3             breast cancer tumor
GSM540112 pT2    2             breast cancer tumor
GSM540113 pT1    2             breast cancer tumor

In [108]:
summarise_rfs_time(datasets[2])

RFS time raw distribution — GSE21653
Column: dfs time (months):ch1

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's
   0.00   28.04   52.91   60.03   89.83  222.29      14

In [109]:
colnames(view_preprocessed(datasets[2]))

[1] "geo_accession" "is_tumor"      "rfs_event"     "rfs_time"

In [110]:
head(view_preprocessed(datasets[2]))

  geo_accession is_tumor rfs_event rfs_time
1 GSM540108     1        1          731.1688
2 GSM540111     1        1         1770.0860
3 GSM540112     1        1          871.1928
4 GSM540113     1        1          301.0516
5 GSM540114     1        1          226.1692
6 GSM540115     1        0         5755.5952

In [111]:
# should be 237

nrow(view_preprocessed(datasets[2]))

[1] 241

In [112]:
head(view_raw_clinical(datasets[3]))

Dataset: GSE20711 | 90 samples x 60 columns

  title                                              [90 unique]  character — e.g. Breast tumor from patient P_1 (expression data), Breast tumor from patient P_2 (expression data), Breast tumor from patient P_3 (expression data) ...
  geo_accession                                      [90 unique]  character — e.g. GSM519722, GSM519723, GSM519724 ...
  status                                             [1 unique]  Public on Oct 19 2011
  submission_date                                    [1 unique]  Mar 09 2010
  last_update_date                                   [1 unique]  Jun 17 2021
  type                                               [1 unique]  RNA
  channel_count                                      [1 unique]  1
  source_name_ch1                                    [2 unique]  Breast tumor | Normal breast tissue
  organism_ch1                                       [1 unique]  Homo sapiens
  characteristics_ch1                                [1 unique]  quality control: 1
  characteristics_ch1.1                              [90 unique]  character — e.g. methylation barcode: 4690141010_D, methylation barcode: 4690141010_J, methylation barcode: 4690141011_A ...
  characteristics_ch1.2                              [5 unique]  subtypeihc: Basal | subtypeihc: HER2 | subtypeihc: LumA | subtypeihc: LumB | subtypeihc: Normal
  characteristics_ch1.3                              [4 unique]  grade: 1 | grade: 2 | grade: 3 | grade: NA
  characteristics_ch1.4                              [3 unique]  node: 0 | node: 1 | node: NA
  characteristics_ch1.5                              [3 unique]  size (bin): 0 | size (bin): 1 | size (bin): NA
  characteristics_ch1.6                              [3 unique]  age (bin): 0 | age (bin): 1 | age (bin): NA
  characteristics_ch1.7                              [3 unique]  er status: 0 | er status: 1 | er status: NA
  characteristics_ch1.8                              [3 unique]  her2 status: 0 | her2 status: 1 | her2 status: NA
  characteristics_ch1.9                              [5 unique]  subtypege: Basal | subtypege: HER2+ | subtypege: LumA | subtypege: LumB | subtypege: NA
  characteristics_ch1.10                             [3 unique]  e.rfs: 0 | e.rfs: 1 | e.rfs: NA
  characteristics_ch1.11                             [86 unique]  character — e.g. t.rfs: 0.93, t.rfs: 1.22, t.rfs: 8.64 ...
  characteristics_ch1.12                             [3 unique]  e.os: 0 | e.os: 1 | e.os: NA
  characteristics_ch1.13                             [88 unique]  character — e.g. t.os: 8.28 y, t.os: 3.39 y, t.os: 8.64 y ...
  molecule_ch1                                       [1 unique]  total RNA
  extract_protocol_ch1                               [1 unique]  Isolation of RNA was performed using the Trizol method (Invitrogen) according to the manufacturers instructions and was purified using RNeasy mini-columns (Qiagen, Valencia, CA). The quality of the RNA obtained from each tumour sample was assessed based on the RNA profile generated by the bioanalyzer (Agilent Inc)olation of RNA was performed using the Trizol method (Invitrogen) according to the manufacturers instructions and was purified using RNeasy mini-columns (Qiagen, Valencia, CA). The quality of the RNA obtained from each tumour sample was assessed based on the RNA profile generated by the bioanalyzer (Agilent Inc).
  label_ch1                                          [1 unique]  biotin
  label_protocol_ch1                                 [1 unique]  Approximately 1 microgram of total RNA was processed to produce biotinylated cRNA targets.
  taxid_ch1                                          [1 unique]  9606
  hyb_protocol                                       [1 unique]  standard Affymetrix procedures.
  scan_protocol                                      [1 unique]  standard Affymetrix procedures.
  description                                        [90 unique]  character — e.g. DNA9194-001.CEL, DNA9194-002.CEL, DNA9194-003.CEL ...
  data_processing                                    [1 unique]  RMA Bioconductor (default parameters) and log2 transformation.
  platform_id                                        [1 unique]  GPL570
  contact_name                                       [1 unique]  Benjamin,,Haibe-Kains
  contact_email                                      [1 unique]  benjamin.haibe.kains@utoronto.ca
  contact_phone                                      [1 unique]  +14165818626
  contact_laboratory                                 [1 unique]  Bioinformatics and Computational Genomics
  contact_department                                 [1 unique]  Princess Margaret Research
  contact_institute                                  [1 unique]  Princess Margaret Cancer Centre
  contact_address                                    [1 unique]  610 University Avenue
  contact_city                                       [1 unique]  Toronto
  contact_state                                      [1 unique]  Ontario
  contact_zip/postal_code                            [1 unique]  M5G 2M9
  contact_country                                    [1 unique]  Canada
  supplementary_file                                 [90 unique]  character — e.g. ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM519nnn/GSM519722/suppl/GSM519722.CEL.gz, ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM519nnn/GSM519723/suppl/GSM519723.CEL.gz, ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM519nnn/GSM519724/suppl/GSM519724.CEL.gz ...
  data_row_count                                     [1 unique]  54675
  age (bin):ch1                                      [3 unique]  0 | 1 | NA
  e.os:ch1                                           [3 unique]  0 | 1 | NA
  e.rfs:ch1                                          [3 unique]  0 | 1 | NA
  er status:ch1                                      [3 unique]  0 | 1 | NA
  grade:ch1                                          [4 unique]  1 | 2 | 3 | NA
  her2 status:ch1                                    [3 unique]  0 | 1 | NA
  methylation barcode:ch1                            [90 unique]  character — e.g. 4690141010_D, 4690141010_J, 4690141011_A ...
  node:ch1                                           [3 unique]  0 | 1 | NA
  quality control:ch1                                [1 unique]  1
  size (bin):ch1                                     [3 unique]  0 | 1 | NA
  subtypege:ch1                                      [5 unique]  Basal | HER2+ | LumA | LumB | NA
  subtypeihc:ch1                                     [5 unique]  Basal | HER2 | LumA | LumB | Normal
  t.os:ch1                                           [88 unique]  character — e.g. 8.28 y, 3.39 y, 8.64 y ...
  t.rfs:ch1                                          [86 unique]  character — e.g. 0.93, 1.22, 8.64 ...

          title                                           geo_accession
GSM519722 Breast tumor from patient P_1 (expression data) GSM519722
GSM519723 Breast tumor from patient P_2 (expression data) GSM519723
GSM519724 Breast tumor from patient P_3 (expression data) GSM519724
GSM519725 Breast tumor from patient P_4 (expression data) GSM519725
GSM519726 Breast tumor from patient P_6 (expression data) GSM519726
GSM519727 Breast tumor from patient P_7 (expression data) GSM519727
          status                submission_date last_update_date type
GSM519722 Public on Oct 19 2011 Mar 09 2010     Jun 17 2021      RNA
GSM519723 Public on Oct 19 2011 Mar 09 2010     Jun 17 2021      RNA
GSM519724 Public on Oct 19 2011 Mar 09 2010     Jun 17 2021      RNA
GSM519725 Public on Oct 19 2011 Mar 09 2010     Jun 17 2021      RNA
GSM519726 Public on Oct 19 2011 Mar 09 2010     Jun 17 2021      RNA
GSM519727 Public on Oct 19 2011 Mar 09 2010     Jun 17 2021      RNA
          channel_count source_name_ch1 organism_ch1 characteristics_ch1 ⋯
GSM519722 1             Breast tumor    Homo sapiens quality control: 1  ⋯
GSM519723 1             Breast tumor    Homo sapiens quality control: 1  ⋯
GSM519724 1             Breast tumor    Homo sapiens quality control: 1  ⋯
GSM519725 1             Breast tumor    Homo sapiens quality control: 1  ⋯
GSM519726 1             Breast tumor    Homo sapiens quality control: 1  ⋯
GSM519727 1             Breast tumor    Homo sapiens quality control: 1  ⋯
          grade:ch1 her2 status:ch1 methylation barcode:ch1 node:ch1
GSM519722 3         1               4690141010_D            1
GSM519723 3         1               4690141010_J            1
GSM519724 3         1               4690141011_A            0
GSM519725 3         0               4690141010_I            1
GSM519726 3         1               4690141011_E            0
GSM519727 3         0               4690141010_K            1
          quality control:ch1 size (bin):ch1 subtypege:ch1 subtypeihc:ch1
GSM519722 1                   1              HER2+         HER2
GSM519723 1                   1              HER2+         HER2
GSM519724 1                   1              HER2+         HER2
GSM519725 1                   1              LumB          LumB
GSM519726 1                   0              Basal         HER2
GSM519727 1                   0              Basal         Basal
          t.os:ch1 t.rfs:ch1
GSM519722 8.28 y   0.93
GSM519723 3.39 y   1.22
GSM519724 8.64 y   8.64
GSM519725 8.4 y    8.4
GSM519726 7.21 y   7.21
GSM519727 8.19 y   7.01

In [113]:
summarise_rfs_time(datasets[3])

Warning message in summarise_rfs_time(datasets[3]):
"NAs introduced by coercion"

RFS time raw distribution — GSE20711
Column: t.rfs:ch1

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's
  0.000   2.560   5.955   5.615   7.933  14.080       2

In [114]:
colnames(view_preprocessed(datasets[3]))

[1] "geo_accession" "is_tumor"      "rfs_event"     "rfs_time"

In [115]:
head(view_preprocessed(datasets[3]))

  geo_accession is_tumor rfs_event rfs_time
1 GSM519722     1        1          339.6825
2 GSM519723     1        1          445.6050
3 GSM519724     1        0         3155.7600
4 GSM519725     1        0         3068.1000
5 GSM519726     1        0         2633.4525
6 GSM519727     1        1         2560.4025

In [116]:
# should be 85

nrow(view_preprocessed(datasets[3]))

[1] 88

In [117]:
head(view_raw_clinical(datasets[4]))

Dataset: GSE88770 | 117 samples x 68 columns

  title                                              [117 unique]  character — e.g. PD9888, PD13139, PD13143 ...
  geo_accession                                      [117 unique]  character — e.g. GSM2345257, GSM2345258, GSM2345259 ...
  status                                             [1 unique]  Public on Oct 15 2016
  submission_date                                    [1 unique]  Oct 14 2016
  last_update_date                                   [1 unique]  Oct 15 2016
  type                                               [1 unique]  RNA
  channel_count                                      [1 unique]  1
  source_name_ch1                                    [4 unique]  ILC, grade 1 | ILC, grade 2 | ILC, grade 3 | ILC, grade not available
  organism_ch1                                       [1 unique]  Homo sapiens
  characteristics_ch1                                [1 unique]  disease status: Invasive lobular carcinoma (ILC)
  characteristics_ch1.1                              [1 unique]  gender: Female
  characteristics_ch1.2                              [1 unique]  tissue: Breast cancer tumor
  characteristics_ch1.3                              [1 unique]  tumor type: ILC
  characteristics_ch1.4                              [5 unique]  subtype: Alveolar | subtype: Classic | subtype: Mixed, non classic | subtype: Solid | subtype: Trabecular
  characteristics_ch1.5                              [19 unique]  character — e.g. positive_nodes: 8, positive_nodes: 2, positive_nodes: 0 ...
  characteristics_ch1.6                              [2 unique]  er: Negative | er: Positive
  characteristics_ch1.7                              [3 unique]  pgr: NA | pgr: Negative | pgr: Positive
  characteristics_ch1.8                              [3 unique]  her2: NA | her2: Negative | her2: Positive
  characteristics_ch1.9                              [30 unique]  character — e.g. ki67: 34, ki67: 10, ki67: 5 ...
  characteristics_ch1.10                             [4 unique]  grade: 1 | grade: 2 | grade: 3 | grade: NA
  characteristics_ch1.11                             [11 unique]  cellularity: 10 | cellularity: 15 | cellularity: 20 | cellularity: 25 | cellularity: 30 | cellularity: 35 | cellularity: 40 | cellularity: 50 | cellularity: 60 | cellularity: 70 | cellularity: 80
  characteristics_ch1.12                             [79 unique]  character — e.g. idfs_or_last_contact_years: 10.9, idfs_or_last_contact_years: 9.7, idfs_or_last_contact_years: 11.2 ...
  characteristics_ch1.13                             [2 unique]  cellularity: No | cellularity: Yes
  characteristics_ch1.14                             [81 unique]  character — e.g. drfs_or_last_contact_years: 10.9, drfs_or_last_contact_years: 9.7, drfs_or_last_contact_years: 12.8 ...
  characteristics_ch1.15                             [2 unique]  drfs_event: No | drfs_event: Yes
  characteristics_ch1.16                             [80 unique]  character — e.g. os_or_last_contact_years: 11.8, os_or_last_contact_years: 10.4, os_or_last_contact_years: 12.8 ...
  characteristics_ch1.17                             [2 unique]  death: No | death: Yes
  characteristics_ch1.18                             [2 unique]  death_disease_specific: No | death_disease_specific: Yes
  treatment_protocol_ch1                             [1 unique]  Not applicable.
  growth_protocol_ch1                                [1 unique]  Not applicable.
  molecule_ch1                                       [1 unique]  total RNA
  extract_protocol_ch1                               [1 unique]  Trizol extraction of total RNA was performed according to the manufacturer's instructions.
  label_ch1                                          [1 unique]  Biotin
  label_protocol_ch1                                 [1 unique]  Biotinylated cRNA were prepared according to the standard Affymetrix protocol from 100 ng total RNA (HuGen U133 Plus 2 array, Affymetrix).
  taxid_ch1                                          [1 unique]  9606
  hyb_protocol                                       [1 unique]  Following fragmentation, 15 ug of cRNA were hybridized for 16 hr at 45C on GeneChip HG133 Plus 2 Array, Affymetrix. GeneChips were washed and stained in the Affymetrix Fluidics Station 450.
  scan_protocol                                      [1 unique]  GeneChips were scanned using Affymetrix GeneChip Scanner GCS3000.
  description                                        [1 unique]  Gene expression data from breast tumor sample.
  data_processing                                    [1 unique]  The probe level intensities were background adjusted using the Robust multi-array analysis (RMA) method followed by quantile normalization as implemented in the R/Bioconductor package frma.
  platform_id                                        [1 unique]  GPL570
  contact_name                                       [1 unique]  Yacine,,Bareche
  contact_email                                      [1 unique]  barechey@gmail.com
  contact_laboratory                                 [1 unique]  BCTL
  contact_institute                                  [1 unique]  Jules Bordet Institute
  contact_address                                    [1 unique]  Rue Héger-Bordetstraat 1
  contact_city                                       [1 unique]  Brussel
  contact_zip/postal_code                            [1 unique]  1000
  contact_country                                    [1 unique]  Belgium
  supplementary_file                                 [117 unique]  character — e.g. ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM2345nnn/GSM2345257/suppl/GSM2345257_d7466e64-c302-432a-8b82-5ba7f7701fbb.CEL.gz, ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM2345nnn/GSM2345258/suppl/GSM2345258_DNA10452-030.CEL.gz, ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM2345nnn/GSM2345259/suppl/GSM2345259_a3fd5ea6-3ce7-4c44-be97-7fe476cc830b.CEL.gz ...
  data_row_count                                     [1 unique]  54675
  cellularity:ch1                                    [19 unique]  character — e.g. 50;Yes, 80;Yes, 25;Yes ...
  death:ch1                                          [2 unique]  No | Yes
  death_disease_specific:ch1                         [2 unique]  No | Yes
  disease status:ch1                                 [1 unique]  Invasive lobular carcinoma (ILC)
  drfs_event:ch1                                     [2 unique]  No | Yes
  drfs_or_last_contact_years:ch1                     [81 unique]  character — e.g. 10.9, 9.7, 12.8 ...
  er:ch1                                             [2 unique]  Negative | Positive
  gender:ch1                                         [1 unique]  Female
  grade:ch1                                          [4 unique]  1 | 2 | 3 | NA
  her2:ch1                                           [3 unique]  NA | Negative | Positive
  idfs_or_last_contact_years:ch1                     [79 unique]  character — e.g. 10.9, 9.7, 11.2 ...
  ki67:ch1                                           [30 unique]  character — e.g. 34, 10, 5 ...
  os_or_last_contact_years:ch1                       [80 unique]  character — e.g. 11.8, 10.4, 12.8 ...
  pgr:ch1                                            [3 unique]  NA | Negative | Positive
  positive_nodes:ch1                                 [19 unique]  character — e.g. 8, 2, 0 ...
  subtype:ch1                                        [5 unique]  Alveolar | Classic | Mixed, non classic | Solid | Trabecular
  tissue:ch1                                         [1 unique]  Breast cancer tumor
  tumor type:ch1                                     [1 unique]  ILC

           title   geo_accession status                submission_date
GSM2345257 PD9888  GSM2345257    Public on Oct 15 2016 Oct 14 2016
GSM2345258 PD13139 GSM2345258    Public on Oct 15 2016 Oct 14 2016
GSM2345259 PD13143 GSM2345259    Public on Oct 15 2016 Oct 14 2016
GSM2345260 PD13148 GSM2345260    Public on Oct 15 2016 Oct 14 2016
GSM2345261 PD9867  GSM2345261    Public on Oct 15 2016 Oct 14 2016
GSM2345262 PD13155 GSM2345262    Public on Oct 15 2016 Oct 14 2016
           last_update_date type channel_count source_name_ch1 organism_ch1
GSM2345257 Oct 15 2016      RNA  1             ILC, grade 2    Homo sapiens
GSM2345258 Oct 15 2016      RNA  1             ILC, grade 3    Homo sapiens
GSM2345259 Oct 15 2016      RNA  1             ILC, grade 2    Homo sapiens
GSM2345260 Oct 15 2016      RNA  1             ILC, grade 2    Homo sapiens
GSM2345261 Oct 15 2016      RNA  1             ILC, grade 1    Homo sapiens
GSM2345262 Oct 15 2016      RNA  1             ILC, grade 2    Homo sapiens
           characteristics_ch1                              ⋯ grade:ch1
GSM2345257 disease status: Invasive lobular carcinoma (ILC) ⋯ 2
GSM2345258 disease status: Invasive lobular carcinoma (ILC) ⋯ 3
GSM2345259 disease status: Invasive lobular carcinoma (ILC) ⋯ 2
GSM2345260 disease status: Invasive lobular carcinoma (ILC) ⋯ 2
GSM2345261 disease status: Invasive lobular carcinoma (ILC) ⋯ 1
GSM2345262 disease status: Invasive lobular carcinoma (ILC) ⋯ 2
           her2:ch1 idfs_or_last_contact_years:ch1 ki67:ch1
GSM2345257 Negative 10.9                           34
GSM2345258 Negative 9.7                            10
GSM2345259 Negative 11.2                           5
GSM2345260 NA       7.3                            18
GSM2345261 Negative 7.9                            11
GSM2345262 Negative 8.6                            67.5
           os_or_last_contact_years:ch1 pgr:ch1  positive_nodes:ch1 subtype:ch1
GSM2345257 11.8                         Positive 8                  Trabecular
GSM2345258 10.4                         Negative 2                  Solid
GSM2345259 12.8                         Negative 0                  Trabecular
GSM2345260 13.7                         Positive 0                  Classic
GSM2345261 14.8                         Positive 2                  Classic
GSM2345262 8.6                          Positive 0                  Trabecular
           tissue:ch1          tumor type:ch1
GSM2345257 Breast cancer tumor ILC
GSM2345258 Breast cancer tumor ILC
GSM2345259 Breast cancer tumor ILC
GSM2345260 Breast cancer tumor ILC
GSM2345261 Breast cancer tumor ILC
GSM2345262 Breast cancer tumor ILC

In [118]:
summarise_rfs_time(datasets[4])

RFS time raw distribution — GSE88770
Column: drfs_or_last_contact_years:ch1

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
  1.200   5.900   8.600   8.745  11.000  17.800

In [119]:
colnames(view_preprocessed(datasets[4]))

[1] "geo_accession" "is_tumor"      "rfs_event"     "rfs_time"

In [120]:
head(view_preprocessed(datasets[4]))

  geo_accession is_tumor rfs_event rfs_time
1 GSM2345257    1        1         3981.225
2 GSM2345258    1        1         3542.925
3 GSM2345259    1        0         4675.200
4 GSM2345260    1        0         5003.925
5 GSM2345261    1        1         2885.475
6 GSM2345262    1        0         3141.150

In [121]:
# should be 113

nrow(view_preprocessed(datasets[4]))

[1] 117

## DEG Datasets: GSE42568 (training)

In [122]:
DEG_STATS <- readRDS(file.path(DEG_DIR, paste0(datasets[1], "_deg_stats.rds")))

cat("deg stats (before filtering): ", nrow(DEG_STATS), "rows\n")
head(DEG_STATS)

deg stats (before filtering):  1557 rows

      gene_symbol logFC     AveExpr  t         P.Value      adj.P.Val
10959 LOC284825   -3.529673 3.781575 -22.30632 7.904608e-45 1.711743e-40
19330 TMEM132C    -2.881126 5.439432 -20.66452 1.265697e-41 1.370433e-37
212   ACADL       -2.997806 3.668408 -20.17125 1.239943e-40 8.950324e-37
279   ACSM5       -2.490258 4.296128 -20.01519 2.568701e-40 1.390630e-36
7774  HSPB7       -1.680985 4.263000 -19.76829 8.182186e-40 3.522458e-36
13932 PDE3B       -3.370559 4.067125 -19.72585 9.992881e-40 3.522458e-36
      B
10959 91.37392
19330 84.12062
212   81.87387
279   81.15648
7774  80.01503
13932 79.81803

In [123]:
DEG_EXPR_RFS <- readRDS(file.path(DEG_DIR, paste0(datasets[1], "_deg_expression_matrix_with_rfs.rds")))

cat("deg expression matrix w/ rfs: ", nrow(DEG_EXPR_RFS), "rows\n")
cat("deg expression matrix w/ rfs: ", ncol(DEG_EXPR_RFS), "cols\n")
head(DEG_EXPR_RFS)

deg expression matrix w/ rfs:  104 rows
deg expression matrix w/ rfs:  266 cols

  geo_accession rfs_time rfs_event ACO1     ADAR     ADIPOQ   AGPAT2   ALDOC
1 GSM1045208    3026     0         4.799942 11.39502 6.075966 6.143011 5.383726
2 GSM1045209     755     1         4.971609 10.86447 8.177897 7.368229 5.854996
3 GSM1045210    3014     0         4.555494 10.94212 6.828506 6.252349 5.317867
4 GSM1045211     406     1         4.668031 10.77627 5.196359 6.861987 6.408760
5 GSM1045212    2225     0         5.458046 11.74328 3.567575 6.902541 8.048325
6 GSM1045213     252     1         4.919103 10.85726 6.905734 6.798690 6.072212
  ANG      ANGPT1   ⋯ UBE2S    VAMP3    VAMP8    VAV3     VIM      VSIG4
1 5.904613 3.628884 ⋯ 4.844556 6.401260 9.204786 5.647802 6.964493 4.966453
2 6.582208 3.702770 ⋯ 6.627002 6.492745 8.080794 4.995820 7.585698 5.970720
3 5.791332 3.630954 ⋯ 4.907463 6.269060 8.533085 5.194826 6.922194 5.289430
4 4.921507 3.693400 ⋯ 5.012260 6.170261 6.865168 5.039221 7.565630 5.307223
5 5.603227 3.580604 ⋯ 7.380517 7.418157 9.662955 5.193608 8.330933 8.333481
6 6.225985 3.927439 ⋯ 5.265401 6.669324 7.972768 5.466955 7.845210 6.225985
  VTCN1     WASF3    XG       ZBTB16
1  7.220646 5.180080 3.151567 3.705057
2  5.437708 4.532965 3.383118 4.551614
3  6.854089 4.636144 3.299654 4.031339
4  5.566723 4.642180 3.480787 4.412832
5 10.065004 5.678931 3.197258 3.402715
6  8.033250 5.390253 3.130131 6.285415

In [124]:
DEG_TF <- readRDS(file.path(DEG_DIR, paste0(datasets[1], "_deg_tf_filtered.rds")))

cat("deg tf filtered: ", nrow(DEG_TF), "rows\n")
head(DEG_TF)

deg tf filtered:  327 rows

      gene_symbol logFC     AveExpr  t         P.Value      adj.P.Val
212   ACADL       -2.997806 3.668408 -20.17125 1.239943e-40 8.950324e-37
17557 SLC19A3     -4.178802 3.710309 -17.92089 6.079842e-36 6.582949e-33
13873 PCK1        -5.138172 3.971325 -17.75122 1.408665e-35 1.452602e-32
12141 MMP28       -1.540415 4.766909 -17.06258 4.425173e-34 3.422397e-31
760   ANGPT1      -2.176110 3.921202 -16.62847 4.006623e-33 2.283248e-30
20129 TWIST2      -1.924945 4.258224 -15.69180 5.022070e-31 2.013943e-28
      B
212   81.87387
17557 71.22174
13873 70.39185
12141 66.98561
760   64.80742
20129 60.02838